apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-chat-config
  labels:
    app: devops-chat
data:
  NEXTAUTH_URL: "http://devops-chat.local"
  LOCAL_USERNAME: "anoop@opsmx.io"
---
apiVersion: v1
kind: Secret
metadata:
  name: devops-chat-secrets
  labels:
    app: devops-chat
type: Opaque
stringData:
  GEMINI_API_KEY: "REPLACE_ME"
  NEXTAUTH_SECRET: "REPLACE_ME"
  LOCAL_PASSWORD_HASH: "REPLACE_WITH_BCRYPT"
